=== TheAncientOwl/book-of-frets-x/project/schemas/song.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Song Schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "version": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+\\.\\d+$",
      "default": "2.0.0"
    },
    "contributors": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "title": {
      "type": "string"
    },
    "artists": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "type": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["acoustic", "electric"]
      }
    },
    "notes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "capo": {
      "type": "integer",
      "minimum": 0
    },
    "chordIDs": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "strumms": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "string",
          "enum": ["D", "U", "-", "Dx", "Ux", "X", "De", "Ue", "|"]
        },
        "minItems": 1
      }
    },
    "sections": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": { "type": "string" },
          "times": { "type": "number", "default": 1, "minimum": 1 },
          "entries": {
            "type": "array",
            "items": {
              "oneOf": [
                {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "renderer": { "type": "string", "enum": ["chords-v1"] },
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                          "times": { "type": "number", "default": 1 },
                          "items": {
                            "type": "array",
                            "items": {
                              "type": "array",
                              "items": {
                                "type": "array",
                                "items": {
                                  "type": "string",
                                  "pattern": "^[0-9]+(?: [A-Za-z0-9#/()_+-|]+ [0-9]+)+$"
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  },
                  "required": ["renderer", "data"]
                },
                {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "renderer": { "type": "string", "enum": ["chords-v2"] },
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "string",
                        "oneOf": [
                          {
                            "pattern": "^x\\d+(?: [A-Za-z0-9#/()_+-|!]+ [0-9]+)+$"
                          },
                          {
                            "pattern": "^>\\s*(?:\\d+\\s*)+$"
                          }
                        ]
                      }
                    }
                  },
                  "required": ["renderer", "data"]
                },
                {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "renderer": { "type": "string", "enum": ["chords-v3"] },
                    "data": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "times": {
                          "type": "number",
                          "default": 1
                        },
                        "items": {
                          "type": "array",
                          "items": {
                            "type": "array",
                            "items": {
                              "type": "string",
                              "oneOf": [
                                {
                                  "pattern": "^x\\d+(?: [A-Za-z0-9#/()_+-|!]+ [0-9]+)+$"
                                },
                                {
                                  "pattern": "^>\\s*(?:\\d+\\s*)+$"
                                }
                              ]
                            }
                          }
                        }
                      },
                      "required": ["times", "items"]
                    }
                  },
                  "required": ["renderer", "data"]
                },
                {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "renderer": { "type": "string", "enum": ["gtab-v1"] },
                    "data": { "type": "string" }
                  },
                  "required": ["renderer", "data"]
                }
              ]
            }
          }
        },
        "required": ["name", "times", "entries"]
      }
    },
    "order": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "lyrics": {
      "type": "boolean",
      "default": false
    },
    "pdf": {
      "type": "boolean",
      "default": false
    },
    "res": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "alias": {
            "type": "string",
            "pattern": ".+"
          },
          "author": {
            "type": "string",
            "pattern": ".+"
          },
          "link": {
            "type": "string",
            "anyOf": [{ "format": "uri" }, { "pattern": "^\\{book-of-frets-x\\}#/.*" }]
          }
        },
        "required": ["alias", "author", "link"]
      }
    }
  },
  "required": [
    "version",
    "contributors",
    "title",
    "artists",
    "type",
    "notes",
    "capo",
    "chordIDs",
    "strumms",
    "sections",
    "order",
    "lyrics",
    "res"
  ]
}

=== TheAncientOwl/book-of-frets-x/public/songs/the-night-we-met-studio/config.json
{
  "version": "2.0.0",
  "contributors": ["TheAncientOwl"],
  "title": "The Night We Met (Studio)",
  "artists": ["Lord Huron"],
  "type": ["electric"],
  "notes": [],
  "capo": 0,
  "chordIDs": ["F#m_9fr", "E_8fr", "A_5fr", "D_5fr"],
  "strumms": [],
  "sections": {
    "i": {
      "name": "intro",
      "times": 2,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "[F#m] - A9 - D11 - G11 - B10 - G11 - D11 - | [E] - A7 - D9 - B9 - | [A] - E5 - A7 - D7 - G6 - D7 - A7 - | - E5 - A7 - D7 - G6 - D7 - A7 -"
        },
        {
          "renderer": "gtab-v1",
          "data": "[F#m] - E2 - A4 - - D4 - - G2 - - D4 - - A4 - - | [A] - E5 - A7 - D7 - | [D] - A5 - D7 - G7 - B7 - G7 - D7 - | - A5 - D7 - G7 - B7 - G7 - D7 -"
        }
      ]
    },
    "c": {
      "name": "chorus",
      "times": 2,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "[F#m] - A9 - D11 - G11 - B10 - G11 - D11 - | [E] - A7 - D9 - B9 - | [A] - E5 - A7 - D7 - G6 - D7 - A7 - | - E5 - A7 - D7 - G6 - D7 - A7 -"
        },
        {
          "renderer": "gtab-v1",
          "data": "[F#m] - E2 - A4 - - D4 - - G2 - - D4 - - A4 - - | [A] - E5 - A7 - D7 - | [D] - A5 - D7 - G7 - B7 - G7 - D7 - | - A5 - D7 - G7 - B7 - G7 - D7 -"
        }
      ]
    },
    "v": {
      "name": "verse",
      "times": 4,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "[F#m] - E2 - A4 - - D4 - - G2 - - D4 - - A4 - - | [A] - E5 - A7 - D7 - | [D] - A5 - D7 - G7 - B7 - G7 - D7 - | - A5 - D7 - G7 - B7 - G7 - D7 -"
        }
      ]
    },
    "vf": {
      "name": "verse",
      "times": 2,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "[F#m] - E2 - A4 - - D4 - - G2 - - D4 - - A4 - - | [A] - E5 - A7 - D7 - | [D] - A5 - D7 - G7 - B7 - G7 - D7 - | - A5 - D7 - G7 - B7 - G7 - D7 -"
        }
      ]
    }
  },
  "order": ["i", "c", "v", "c", "v", "c", "vf"],
  "lyrics": false,
  "pdf": false,
  "res": [
    {
      "alias": "The Night We Met Guitar Tutorial 🎸 Lord Huron Guitar Lesson |Easy Chords + Picking + TAB|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/XEYpA3vj1bA"
    },
    {
      "alias": "The Night We Met Guitar Cover Lord Huron 🎸|Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/9YjBCrY_-1s"
    }
  ]
}

=== TheAncientOwl/book-of-frets-x/songs/o-stea/config.json
{
  "version": "2.0.0",
  "contributors": ["TheAncientOwl"],
  "title": "O Stea",
  "artists": ["Deepcentral"],
  "type": ["acoustic"],
  "notes": ["Drop D"],
  "capo": 0,
  "chordIDs": ["Em7", "Cadd9", "G", "D"],
  "strumms": [["D", "D", "-", "U", "U", "-", "D", "-", "U", "-", "D", "U"]],
  "sections": {
    "m": {
      "name": "main progression",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 404,
              "items": [[["0 Em7 1 Cadd9 1 G 1 D 1"]]]
            }
          ]
        }
      ]
    }
  },
  "order": ["m"],
  "lyrics": false,
  "pdf": false,
  "res": [
    {
      "alias": "CUM SĂ CÂNȚI \"O STEA\" LA CHITARA!? (DEEPCENTRAL)",
      "author": "Cantam La Chitara ~ YouTube",
      "link": "https://youtu.be/kuhMWv4uNCk"
    }
  ]
}

=== TheAncientOwl/book-of-frets-x/songs/radioactive/config.json
{
  "version": "2.0.0",
  "contributors": ["TheAncientOwl"],
  "title": "Radioactive",
  "artists": ["Imagine Dragons"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 2,
  "chordIDs": ["Am", "C", "G", "D"],
  "strumms": [
    ["D", "-", "D", "-", "U", "D", "U"],
    ["D", "U", "D", "U", "D", "-", "D", "U"]
  ],
  "sections": {
    "i": {
      "name": "intro",
      "times": 3,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["0 Am 1 C 1 G 1 D 1"]]]
            }
          ]
        }
      ]
    },
    "v": {
      "name": "verse",
      "times": 3,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["1 Am 1 C 1 G 1 D 1"]]]
            }
          ]
        }
      ]
    }
  },
  "order": ["i", "v"],
  "lyrics": false,
  "pdf": false,
  "res": [
    {
      "alias": "Radioactive Guitar Tutorial - Imagine Dragons Guitar Lesson |Easy Chords + Guitar Cover|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://www.youtube.com/watch?v=l2KR3vvgqB0"
    },
    {
      "alias": "Radioactive Guitar Cover Acoustic - Imagine Dragons 🎸 |Guitar Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/wQKXwxXvMMA"
    }
  ]
}

=== TheAncientOwl/book-of-frets-x/public/songs/stay/config.json
{
  "version": "2.0.1",
  "contributors": ["TheAncientOwl"],
  "title": "Stay",
  "artists": ["The Kid LAROI", "Justin Bieber"],
  "type": ["electric"],
  "notes": [],
  "capo": 0,
  "chordIDs": [],
  "strumms": [],
  "sections": {
    "i": {
      "name": "intro",
      "times": 1,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "- G5/6 - G6 - B9 - - - - - G6 - G6 - | - G5 - G5 - G5 - G5 - G5 - G6 - G6 - - - | - G5/6 - G6 - B9 - - - - - G6 - G6 - | - G5 - G5 - G5 - G5 - G5 - G6 - G6 - - -"
        },
        {
          "renderer": "gtab-v1",
          "data": "- G5/6 - G6 - B9 - - - - - G6 - G6 - | - G5 - G5 - G5 - G5 - G5 - G6 - G6 - - - | - G5/6 - G6 - B9 - - - - - G6/8 - | - G8 - e8 - - - - - G9~ - - - - - -"
        }
      ]
    },
    "v1": {
      "name": "verse 1",
      "times": 1,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "- - - G10\\ - - G6/8 - - - G8 - - | - - - - G8 - - G6 - G8 - - G8 - - - - | - D8 - G10\\ - - G6/8 - - - G8 - - | - - - G8 - - - G6 - G8 - - - G8 - - -"
        },
        {
          "renderer": "gtab-v1",
          "data": "- D8 - G10\\ - - G6/8 - - - G8 - - | - - - G8 - - - G6 - G8 - - - G8 - - - | - B9 - - - B6 - - - B9 - - - B6 - - - | - G8 - G8 - G8 - B6 - G8^ B^ G^6 - - -"
        }
      ]
    },
    "pc": {
      "name": "prechorus",
      "times": 1,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "- G5/6 - - - - D8 - G8/10 - - - | - G10 - - - - - - - - - - - - - - | - G5/6 - - - - D8 - G8/10 - - - | - G10 - - - - - - - - - - - - - -"
        },
        {
          "renderer": "gtab-v1",
          "data": "- G5/6 - - - - D8 - G8/10 - - - | - G10 - - - - - - - - - - - - - - | - B9 - - - B6 - - - B9 - - - B6 - - - | - G8 - G8 - G8 - B6 - G8^ B^ G^6 - - -"
        }
      ]
    },
    "c": {
      "name": "chorus",
      "times": 2,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "- G5/6 - G6 - B9 - - - - - G6 - G6 - | - G5 - G5 - G5 - G5 - G5 - G6 - G6 - - - | - G5/6 - G6 - B9 - - - - - G6 - G6 - | - G5 - G5 - G5 - G5 - G5 - G6 - G6 - - -"
        },
        {
          "renderer": "gtab-v1",
          "data": "- G5/6 - G6 - B9 - - - - - G6 - G6 - | - G5 - G5 - G5 - G5 - G5 - G6 - G6 - - - | - G5/6 - G6 - B9 - - - - - G6/8 - | - G8 - e8 - - - - - B9~ - - - - - -"
        }
      ]
    },
    "v2": {
      "name": "verse 2",
      "times": 1,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "- - B6 - B6 - B6 - B6 - G6 - G6 - G6 - - | - G6 - G8 - G8~ - - - - - - - - - - | - - B6 - B6 - B6 - B6 - G6 - G6 - G6 - - | - G6 - G8 - G8 - - - - G6 - G8 - G6 - -"
        },
        {
          "renderer": "gtab-v1",
          "data": "- - B6 - B6 - B6 - B6 - G6 - G6 - G6 - - | - G6 - G8 - G8~ - - - - - - - - - - | - - B6 - B6 - B6 - B6 - G6 - G6 - G6 - - | - G6 - G8 - G8 - - - - G6 - G8 - G6 - -"
        },
        {
          "renderer": "gtab-v1",
          "data": "- - e8 - e8 - e9 - - - G8 - G8 - G6 - - | - G8 - - G8 - G6 - G8 - - G8/10 - - | - - G8 - G8 - G6 - G8 - G8 - G8 - G6 - - | - - G8 - - G8/10 - - G5 - - G6 - -"
        },
        {
          "renderer": "gtab-v1",
          "data": "- - G6 - B6 - G8 - - - G6 - B6 - G8 - - | - - G8 - G6 - B6 - G8 - - - D8 - - - - | - - G6 - G6 - G6 - G6 - G6/8 - - e8 - | - e6 - - B9 - - - - - - - - - - - -"
        }
      ]
    },
    "o": {
      "name": "outro",
      "times": 1,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "- G- - - - - - - - - - - - - - - - | - G- - - - - - - - - - - - - - - - | - G5/6 - G6 - B9 - - - - - G6/8 - | - G8 - e8 - - - - - B9~ - - - - - -"
        }
      ]
    }
  },
  "order": ["i", "v1", "pc", "c", "v2", "pc", "c", "o"],
  "lyrics": false,
  "pdf": false,
  "res": [
    {
      "alias": "Stay - The Kid LAROI, Justin Bieber - Instrumental Guitar Cover + TAB",
      "author": "gitar online",
      "link": "https://youtu.be/JjOYiWvLgdQ"
    }
  ]
}

=== TheAncientOwl/book-of-frets-x/public/songs/save-your-tears/config.json
{
  "version": "2.0.0",
  "contributors": ["TheAncientOwl"],
  "title": "Save Your Tears",
  "artists": ["The Weekend", "Ariana Grande"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 0,
  "chordIDs": ["C", "Am", "Em", "G", "Ft"],
  "strumms": [
    ["D", "-", "D", "-", "De", "-", "D", "-", "D", "-", "D", "-", "De", "-", "D", "-"],
    ["D", "D"],
    ["D", "U", "D", "U", "D", "U", "D", "U"],
    ["D", "U", "D", "U", "D", "-", "-", "-"],
    ["D", "-", "D", "-", "D", "-", "D", "-"],
    ["D"]
  ],
  "sections": {
    "i": {
      "name": "intro",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["0 C 4"]]]
            }
          ]
        }
      ]
    },
    "v1": {
      "name": "verse 1",
      "times": 8,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["0 C 1 Am 1 Em 1 G 1"]]]
            }
          ]
        }
      ]
    },
    "pr1": {
      "name": "prechorus 1",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["0 Dm 1 Am 1 Ft 1 G 1"]]]
            }
          ]
        }
      ]
    },
    "c1": {
      "name": "chorus 1",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["1 C 1 Am 1"], ["2 Em 1 G 1"]]]
            },
            {
              "times": 1,
              "items": [[["1 C 1 Am 1"], ["2 Em 1"], ["3 G 1"]]]
            }
          ]
        }
      ]
    },
    "v2": {
      "name": "verse 2",
      "times": 4,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["0 C 1 Am 1 Em 1 G 1"]]]
            }
          ]
        }
      ]
    },
    "pr2": {
      "name": "prechorus 2",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["0 Dm 1 Am 1 Ft 1"]]]
            },
            {
              "times": 1,
              "items": [[["4 F 1 G 1"]]]
            },
            {
              "times": 1,
              "items": [[["0 Dm 1 Am 1 Ft 1 G 1"]]]
            }
          ]
        }
      ]
    },
    "b": {
      "name": "bridge",
      "times": 2,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["5 C 1 Am 1 Em 1 G 1"]]]
            }
          ]
        }
      ]
    },
    "c2": {
      "name": "chorus 2",
      "times": 4,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["2 C 1 Am 1 Em 1 G 1"]]]
            }
          ]
        }
      ]
    }
  },
  "order": ["i", "v1", "pr1", "c1", "v2", "pr2", "c1", "b", "c2"],
  "lyrics": false,
  "pdf": false,
  "res": [
    {
      "alias": "Save Your Tears Guitar Tutorial The Weeknd Guitar Lesson |Easy Chords|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/aPuujELV4Hg"
    },
    {
      "alias": "Save Your Tears Guitar Cover The Weeknd 🎸|Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/NF-gjc8-fz0?"
    }
  ]
}

=== TheAncientOwl/book-of-frets-x/public/songs/flowers-need-rain/config.json
{
  "version": "2.0.0",
  "contributors": ["TheAncientOwl"],
  "title": "Flowers Need Rain",
  "artists": ["Preston Pablo"],
  "type": ["acoustic", "electric"],
  "notes": [],
  "capo": 0,
  "chordIDs": ["-"],
  "strumms": [],
  "sections": {
    "m": {
      "name": "main",
      "times": 404,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "- E9 - - A9 - - E9 - - A9 - - E9 - - A9 - - E9 - - A9 - | - E5 - - A6 - - E5 - - A6 - - E5 - - A6 - - E5 - - A6 - | - E12 - - A13 - - E12 - - A13 - - E12 - - A13 - - E12 - - A13 - | - E7 - - A8 - - E7 - - A8 - - E7 - - A8 - - E7 - - A8 -"
        }
      ]
    }
  },
  "order": ["m"],
  "lyrics": false,
  "pdf": false,
  "res": [
    {
      "alias": "How to play Flowers Need Rain by Preston Pablo",
      "author": "Elijah Plays ~ YouTube",
      "link": "https://youtu.be/Bl4FiG65g1A"
    }
  ]
}

=== TheAncientOwl/book-of-frets-x/public/songs/dusk-till-dawn/config.json
{
  "version": "2.1.0",
  "contributors": ["TheAncientOwl"],
  "title": "Dusk Till Dawn",
  "artists": ["Zayn", "Sia"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 2,
  "chordIDs": ["Am", "Ft", "C", "G/B", "Em", "C/E"],
  "strumms": [
    ["D"],
    ["D", "D", "D", "D", "De", "D", "D", "D"],
    ["D", "-", "-", "-", "D", "-", "D", "U"],
    ["D", "-", "D", "-", "D", "-", "D", "U"]
  ],
  "sections": {
    "vpi": {
      "name": "verse / prechorus",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": [
            "x3 Am 1 F 1 C 1 G/B 1",
            "> 0",
            "x1 Am 1 F 1 C 1 G/B 1",
            "> 1",
            "x2 Am 1 F 1 C 1 G/B 1",
            "> 0"
          ]
        }
      ]
    },
    "c": {
      "name": "chorus",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x1 Am 1", "> 2", "x4 Am 2 F 2 C 2 Em 2", "> 3"]
        }
      ]
    },
    "bk": {
      "name": "break",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x1 Am 1", "> 0"]
        }
      ]
    },
    "vp": {
      "name": "verse / prechorus",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x3 Am 1 F 1 C 1 G/B 1", "> 1", "x2 Am 1 F 1 C 1 G/B 1", "> 0"]
        }
      ]
    },
    "b": {
      "name": "bridge",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": [
            "x1 F 1 | 0 F 1 C 1 | 0 C 1 G 1 | 0 G 1 C/E 1",
            "x1 F 1 | 0 F 1 C 1 | 0 C 1 G 1 | 0 G 1 G 1",
            "> 0"
          ]
        }
      ]
    }
  },
  "order": ["vpi", "c", "bk", "vp", "c", "b", "c"],
  "lyrics": false,
  "pdf": false,
  "res": [
    {
      "alias": "Dusk Till Dawn Guitar Tutorial - Zayn feat Sia Guitar Lesson 🎸 |Chords + No Capo + Guitar Cover|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/v2AMU6dh0pA"
    },
    {
      "alias": "Dusk Till Dawn Guitar Cover Acoustic - Zayn Feat Sia 🎸 |Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/qT8s6mvDzxw"
    }
  ]
}

=== TheAncientOwl/book-of-frets-x/public/songs/california-dreaming/config.json
{
  "version": "2.1.0",
  "contributors": ["TheAncientOwl"],
  "title": "California Dreamin'",
  "artists": ["The Mamas & The Papas"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 4,
  "chordIDs": ["Am", "C", "F", "G", "E7", "E7sus4"],
  "strumms": [["D", "U", "D", "U"], ["D"]],
  "sections": {
    "i1": {
      "name": "intro guitar 1",
      "times": 1,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "[Asus2] - D2 - G2 - B0 - D2 - B3 - B1 - B0 - | - D2 - G2 - B0 - D2 - B3 - B1 - B0 - | - D2 - G2 - B0 - D2 - B3 - B1 - B0 - | [E7sus4] - E0+A2+D0+G2+B0+e0 - - - - - - - - - - - - -"
        }
      ]
    },
    "i2": {
      "name": "intro guitar 2",
      "times": 1,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "[Asus2] - - - - - - - - - - - - - - - | - - - - - e0 - e1 - e1 - - B3 - - | - B1 - - B2 - B1 - B0 - G2 - - G0 - | [E7sus4] - E0+A2+D0+G2+B0+e0 - - - - - - - - - - - - -"
        }
      ]
    },
    "v1": {
      "name": "verse 1",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": [
            "x1 Am 1 G 1 | 0 F 1 G 1 / 0 E7sus4 1 E7sus4 1 | 0 E7 1 F 1",
            "x1 C 1 E7 1 | 0 Am 1 F 1 / 0 E7sus4 1 E7sus4 1 | 0 E7 1 E7 1",
            "x2 Am 1 G 1 | 0 F 1 G 1 / 0 E7sus4 1 E7sus4 1 | 0 E7 1 E7 1",
            "> 0"
          ]
        }
      ]
    },
    "v2": {
      "name": "verse 2",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": [
            "x1 Am 1 G 1 | 0 F 1 G 1 / 0 E7sus4 1 E7sus4 1 | 0 E7 1 F 1",
            "x1 C 1 E7 1 | 0 Am 1 F 1 / 0 E7sus4 1 E7sus4 1 | 0 E7 1 E7 1",
            "x2 Am 1 G 1 | 0 F 1 G 1 / 0 E7sus4 1 E7sus4 1 | 0 E7 1 E7 1",
            "> 0"
          ]
        }
      ]
    },
    "s": {
      "name": "solo",
      "times": 1,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "- G5▲ - - - - - - - - - - - - | - G▼5 - - G4 - G5 - G5/7 - - G5^4 - | - G5▲ - - - - - - - - - - - - | - G▼5 - - G4 - G5 - G5/7 - - G5^4"
        },
        {
          "renderer": "gtab-v1",
          "data": "- D5 - - - - - - D6 - - - - - - | - D7 - - - - - - B6 - - - - - - | - B5 - - - - - - - - G7/5 - | - G7/9 - - B5 - e5 - - e7 - - e5 - e7 - e5 - B8 -"
        },
        {
          "renderer": "gtab-v1",
          "data": "- e5 - - e5 - - B8 - - B8 - B6▲ - | - B▼6 - - e5 - - e7 - - e5 - - B8 - - B5▲ - | - B▼5 - - - G7/5 - G7/9▲ - | - G▼9 - - - G9 - B8 - e7 - - e7 -"
        },
        {
          "renderer": "gtab-v1",
          "data": "- e8 - - e8 - - e7 - - e7 - e5▲ - | - e▼5 - - e8 - - e5 - - e8 - - e8 - - - e7▲ - | - e▼7 - - e10 - e10 - e7 - e7 - B9 - | - B9 - B6 - B6 - B5 - B5 - B6 - B5 -"
        }
      ]
    },
    "v3": {
      "name": "verse 3",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": [
            "x1 Am 1 G 1 | 0 F 1 G 1 / 0 E7sus4 1 E7sus4 1 | 0 E7 1 F 1",
            "x1 C 1 E7 1 | 0 Am 1 F 1 / 0 E7sus4 1 E7sus4 1 | 0 E7 1 E7 1",
            "x1 Am 1 G 1 | 0 F 1 G 1 / 0 E7sus4 1 E7sus4 1 | 0 E7 1 E7 1",
            "> 0"
          ]
        }
      ]
    },
    "o": {
      "name": "outro",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x3 Am 1 G 1 | 0 F 1 G 1", "x1 F 1 F 1 | 0 F 1 F 1", "> 0", "x1 Am 1", "> 1"]
        }
      ]
    }
  },
  "order": ["i1", "i2", "v1", "v2", "s", "v3", "o"],
  "lyrics": false,
  "pdf": false,
  "res": [
    {
      "alias": "California Dreamin’ Guitar Tutorial The Mamas & The Papas Lesson | Chords + Strumming + Solo |",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/SnU7gwkvtE8"
    }
  ]
}
