=== TheAncientOwl/book-of-frets-x/project/schemas/song.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Song Schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "version": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+\\.\\d+$",
      "default": "2.0.0"
    },
    "contributors": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "title": {
      "type": "string"
    },
    "artists": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "type": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["acoustic", "electric"]
      }
    },
    "notes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "capo": {
      "type": "integer",
      "minimum": 0
    },
    "chordIDs": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "strumms": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "string",
          "enum": ["D", "U", "-", "Dx", "Ux", "X", "De", "Ue", "|"]
        },
        "minItems": 1
      }
    },
    "sections": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": { "type": "string" },
          "times": { "type": "number", "default": 1, "minimum": 1 },
          "entries": {
            "type": "array",
            "items": {
              "oneOf": [
                {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "renderer": { "type": "string", "enum": ["chords-v1"] },
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                          "times": { "type": "number", "default": 1 },
                          "items": {
                            "type": "array",
                            "items": {
                              "type": "array",
                              "items": {
                                "type": "array",
                                "items": {
                                  "type": "string",
                                  "pattern": "^[0-9]+(?: [A-Za-z0-9#/()_+-|]+ [0-9]+)+$"
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  },
                  "required": ["renderer", "data"]
                },
                {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "renderer": { "type": "string", "enum": ["chords-v2"] },
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "string",
                        "oneOf": [
                          {
                            "pattern": "^x\\d+(?: [A-Za-z0-9#/()_+-|!]+ [0-9]+)+$"
                          },
                          {
                            "pattern": "^>\\s*(?:\\d+\\s*)+$"
                          }
                        ]
                      }
                    }
                  },
                  "required": ["renderer", "data"]
                },
                {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "renderer": { "type": "string", "enum": ["chords-v3"] },
                    "data": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "times": {
                          "type": "number",
                          "default": 1
                        },
                        "items": {
                          "type": "array",
                          "items": {
                            "type": "array",
                            "items": {
                              "type": "string",
                              "oneOf": [
                                {
                                  "pattern": "^x\\d+(?: [A-Za-z0-9#/()_+-|!]+ [0-9]+)+$"
                                },
                                {
                                  "pattern": "^>\\s*(?:\\d+\\s*)+$"
                                }
                              ]
                            }
                          }
                        }
                      },
                      "required": ["times", "items"]
                    }
                  },
                  "required": ["renderer", "data"]
                },
                {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "renderer": { "type": "string", "enum": ["gtab-v1"] },
                    "data": { "type": "string" }
                  },
                  "required": ["renderer", "data"]
                }
              ]
            }
          }
        },
        "required": ["name", "times", "entries"]
      }
    },
    "order": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "lyrics": {
      "type": "boolean",
      "default": false
    },
    "pdf": {
      "type": "boolean",
      "default": false
    },
    "res": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "alias": {
            "type": "string",
            "pattern": ".+"
          },
          "author": {
            "type": "string",
            "pattern": ".+"
          },
          "link": {
            "type": "string",
            "anyOf": [{ "format": "uri" }, { "pattern": "^\\{book-of-frets-x\\}#/.*" }]
          }
        },
        "required": ["alias", "author", "link"]
      }
    }
  },
  "required": [
    "version",
    "contributors",
    "title",
    "artists",
    "type",
    "notes",
    "capo",
    "chordIDs",
    "strumms",
    "sections",
    "order",
    "lyrics",
    "res"
  ]
}

=== TheAncientOwl/book-of-frets-x/public/songs/beautiful-people/config.json
{
  "version": "2.1.0",
  "contributors": ["TheAncientOwl"],
  "title": "Beautiful People",
  "artists": ["Ed Sheeran", "Khalid"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 3,
  "chordIDs": ["C", "Am", "F", "Em"],
  "strumms": [
    ["D", "-", "-", "-", "D", "-", "D", "U", "-", "U", "D", "-", "D", "-", "D", "U"],
    ["D", "-", "-", "-", "D", "-", "D", "U", "-", "U"],
    ["D", "-", "D", "-", "D", "U"],
    ["D"]
  ],
  "sections": {
    "i": {
      "name": "intro",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x1 C 1 C 1", "> 0"]
        }
      ]
    },
    "m4": {
      "name": "main progression",
      "times": 4,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x1 Am 1 C 1 F 1", "> 0"]
        },
        {
          "renderer": "chords-v2",
          "data": ["x1 F 1 ? 0 Em 1", "> 1 2"]
        }
      ]
    },
    "p": {
      "name": "pre",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x1 Am 1 C 1 ? 0 F 1", "> 0 3"]
        }
      ]
    },
    "m3": {
      "name": "main progression",
      "times": 3,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x1 Am 1 C 1 F 1", "> 0"]
        },
        {
          "renderer": "chords-v2",
          "data": ["x1 F 1 ? 0 Em 1", "> 1 2"]
        }
      ]
    },
    "o": {
      "name": "outro",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x1 Am 1 C 1 F 1", "> 3"]
        }
      ]
    }
  },
  "order": ["i", "m4", "p", "m4", "m3", "p", "m4", "o"],
  "lyrics": false,
  "pdf": false,
  "res": [
    {
      "alias": "Beautiful People Guitar Tutorial 🎸 Ed Sheeran Guitar Lesson |Easy Chords|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/caqQxg4cwDY"
    },
    {
      "alias": "Beautiful People Guitar Cover Ed Sheeran 🎸 |Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/tlQvOA52XSc"
    }
  ]
}

=== TheAncientOwl/book-of-frets-x/songs/all-i-want-for-christmas-is-you/config.json
{
  "version": "2.0.0",
  "contributors": ["TheAncientOwl"],
  "title": "All I Want For Christmas Is You",
  "artists": ["Mariah Carey"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 0,
  "chordIDs": ["G", "Em", "C", "D", "G/B", "Cm_3fr", "B7", "D7", "E7", "Am7"],
  "strumms": [["D"], ["D", "U"]],
  "sections": {
    "ibd": {
      "name": "intro",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["0 G 1 Em 1 C 1 D 1"]]]
            }
          ]
        }
      ]
    },
    "sv": {
      "name": "slow verse",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [
                [["0 C 1 G/B 1 C 1 Cm_3fr 1", "0 G 1 B7 1 Em 1 Cm_3fr 1", "0 G 1 E7 1 Am7 1 D7 1"]]
              ]
            }
          ]
        }
      ]
    },
    "ibs": {
      "name": "break",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["1 G 4 Em 4 C 4 D 4"]]]
            }
          ]
        }
      ]
    },
    "v": {
      "name": "verse",
      "times": 2,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["1 G 16 C 8 Cm_3fr 8"]]]
            }
          ]
        }
      ]
    },
    "c": {
      "name": "chorus",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["1 G 6 B7 2 Em 6 Cm_3fr 1", "0 G 4 E7 4 Am7 4 D7 4"]]]
            }
          ]
        }
      ]
    },
    "b": {
      "name": "bridge",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 2,
              "items": [[["1 B7 8 Em 8 Cm_3fr 8", "0 G 4 E7 4 Am7 8 D 8"]]]
            }
          ]
        }
      ]
    }
  },
  "order": ["ibd", "sv", "ibs", "v", "ibs", "v", "c", "ibs", "b", "v", "c", "ibs"],
  "lyrics": false,
  "pdf": false,
  "res": [
    {
      "alias": "All I Want For Christmas Is You Guitar Tutorial 🎄🎸Mariah Carey Guitar Lesson |Easy Chords|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/2PZGR5vRDFE"
    },
    {
      "alias": "All I Want For Christmas Is You Guitar Cover Mariah Carey 🎸|Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/bkDlng69K20"
    }
  ]
}

=== TheAncientOwl/book-of-frets-x/public/songs/i-miss-you-solo-ac/config.json
{
  "version": "2.1.0",
  "contributors": ["TheAncientOwl"],
  "title": "I Miss You (Solo Acoustic)",
  "artists": ["Blink-182"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 4,
  "chordIDs": ["G", "G/F#", "Em7", "A7sus4", "C", "Dsus2"],
  "strumms": [
    ["D", "-", "D", "-", "D", "-", "D", "U", "-", "U", "D", "-", "D", "-", "D", "U"],
    ["D", "-", "D", "-", "D", "-", "D"],
    ["U", "-", "U", "D", "-", "D", "-", "D", "U"],
    ["D"]
  ],
  "sections": {
    "i": {
      "name": "intro",
      "times": 2,
      "entries": [{ "renderer": "chords-v2", "data": ["x1 G 1 G/F# 1 Em7 1 G/F# 1", "> 0"] }]
    },
    "v1": {
      "name": "verse 1",
      "times": 3,
      "entries": [{ "renderer": "chords-v2", "data": ["x1 G 1 G/F# 1 Em7 1 G/F# 1", "> 0"] }]
    },
    "c": {
      "name": "chorus",
      "times": 2,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x1 G 1 ? 0 A7sus4 1", "x1 G/B 1 ? 0 Dsus2 1", "> 1 2"]
        },
        { "renderer": "chords-v2", "data": ["x1 C 1 C 1", "> 0"] }
      ]
    },
    "b1": {
      "name": "break 1",
      "times": 1,
      "entries": [{ "renderer": "chords-v2", "data": ["x1 G 1 - 1", "> 3"] }]
    },
    "v2": {
      "name": "verse 2",
      "times": 4,
      "entries": [{ "renderer": "chords-v2", "data": ["x1 G 1 G/F# 1 Em7 1 G/F# 1", "> 0"] }]
    },
    "b2": {
      "name": "break 2",
      "times": 1,
      "entries": [{ "renderer": "chords-v2", "data": ["x1 G 1 G 1", "> 0"] }]
    },
    "bg": {
      "name": "bridge",
      "times": 2,
      "entries": [{ "renderer": "chords-v2", "data": ["x1 Em7 1 G/F# 1 G 1 G/F# 1", "> 0"] }]
    },
    "cf": {
      "name": "chorus",
      "times": 6,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x1 G 1 ? 0 A7sus4 1", "x1 G/B 1 ? 0 Dsus2 1", "> 1 2"]
        },
        {
          "renderer": "chords-v2",
          "data": ["x1 C 1 C 1", "> 0"]
        }
      ]
    }
  },
  "order": ["i", "v1", "c", "b1", "v2", "c", "b2", "bg", "cf"],
  "lyrics": false,
  "pdf": false,
  "res": [
    {
      "alias": "I Miss You Guitar Tutorial Blink -182 Guitar Lesson Chords + TAB",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/kYsyB9xASyU"
    },
    {
      "alias": "I Miss You Guitar Cover Blink-182 🎸|Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/SWkhIRk-bH4"
    }
  ]
}

=== TheAncientOwl/book-of-frets-x/public/songs/without-you/config.json
{
  "version": "2.1.0",
  "contributors": ["TheAncientOwl"],
  "title": "Without You",
  "artists": ["The Kid LAROI"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 0,
  "chordIDs": ["Am", "F", "C", "G", "E"],
  "strumms": [
    ["Dx", "-", "Dx", "-", "Dx", "-", "Dx", "Ux"],
    ["D", "-", "-", "-", "D", "-", "-", "U", "-", "U", "D", "-", "D", "-", "D", "U"],
    ["D", "-", "D", "-", "D", "-", "D", "-", "D", "-", "-", "-", "Dx", "Ux", "Dx", "Ux"],
    ["D"],
    ["D", "-", "D", "-", "D", "-", "D", "-", "D", "-", "D", "-", "D", "-", "D", "U"],
    ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "Dx", "Ux", "Dx", "Ux"]
  ],
  "sections": {
    "i": {
      "name": "intro",
      "times": 1,
      "entries": [
        { "renderer": "chords-v2", "data": ["x1 - 1", "> 0", "x1 Am 1 F 1 C 1 G 1", "> 1"] }
      ]
    },
    "c1": {
      "name": "chorus",
      "times": 1,
      "entries": [{ "renderer": "chords-v2", "data": ["x2 Am 1 F 1 C 1 G 1", "> 1"] }]
    },
    "v": {
      "name": "verse",
      "times": 1,
      "entries": [{ "renderer": "chords-v2", "data": ["x2 Am 1 F 1 C 1 G 1", "> 1"] }]
    },
    "pr1": {
      "name": "prechorus 1",
      "times": 1,
      "entries": [{ "renderer": "chords-v2", "data": ["x1 Am 1 F 1 C 1", "> 1", "x1 E 1", "> 2"] }]
    },
    "c2": {
      "name": "chorus",
      "times": 1,
      "entries": [{ "renderer": "chords-v2", "data": ["x1 Am 1 F 1 C 1 G 1", "> 1"] }]
    },
    "b": {
      "name": "bridge",
      "times": 1,
      "entries": [{ "renderer": "chords-v2", "data": ["x1 Am 1 F 1 C 1", "> 3", "x1 G 1", "> 4"] }]
    },
    "pr2": {
      "name": "prechorus 2",
      "times": 1,
      "entries": [{ "renderer": "chords-v2", "data": ["x1 Am 1 F 1 C 1", "> 1", "x1 - 1", "> 5"] }]
    },
    "o": {
      "name": "outro",
      "times": 1,
      "entries": [{ "renderer": "chords-v2", "data": ["x1 Am 1 F 1 C 1 G 1", "> 3"] }]
    }
  },
  "order": ["i", "c1", "v", "pr1", "c2", "b", "pr2", "c1", "o"],
  "lyrics": false,
  "pdf": false,
  "res": [
    {
      "alias": "Without You Guitar Tutorial The Kid LAROI Lesson |Easy Chords + Cover|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/I8UfGA0qR7A"
    },
    {
      "alias": "Without You Guitar Cover The Kid LAROI 🎸|Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/ayhT2swtB0w"
    }
  ]
}

=== TheAncientOwl/book-of-frets-x/public/songs/flake/config.json
{
  "version": "2.1.0",
  "contributors": ["TheAncientOwl"],
  "title": "Flake",
  "artists": ["Jack Johnson"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 0,
  "chordIDs": ["Dm_5fr", "F_1fr", "Bb_6fr", "C_8fr", "C_3fr", "A_5fr", "Bb_1fr"],
  "strumms": [
    ["D", "-", "D", "U", "Dx", "Ux", "Dx", "U", "-", "U", "-", "U", "Dx", "Ux", "Dx", "Ux"],
    ["D"],
    ["D", "Ux", "D", "Ux", "D", "Ux", "D", "Ux", "D", "Ux", "D", "Ux", "D", "Ux", "D", "Ux"],
    ["D", "Ux", "D", "Ux", "D", "Ux", "D", "Ux"]
  ],
  "sections": {
    "i": {
      "name": "intro",
      "times": 2,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x2 Dm_5fr 1 F_1fr 1 Bb_6fr 1 F_1fr 1", "> 0"]
        }
      ]
    },
    "v": {
      "name": "verse",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": [
            "x3 Dm_5fr 1 F_1fr 1 Bb_6fr 1 F_1fr 1",
            "x1 Dm_5fr 1 F_1fr 1 Bb_6fr 1 C_8fr 1",
            "> 0"
          ]
        }
      ]
    },
    "c1": {
      "name": "chorus 1",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": [
            "x2 F_1fr 1 C_3fr 1 Dm_5fr 1 A_5fr 1 / 0 Bb_6fr 1 C_8fr 1 F_1fr 1 C_8fr 1",
            "> 0"
          ]
        }
      ]
    },
    "v2": {
      "name": "verse",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": [
            "x2 Dm_5fr 1 F_1fr 1 Bb_6fr 1 F_1fr 1",
            "> 1",
            "x1 Dm_5fr 1 F_1fr 1 Bb_6fr 1 F_1fr 1",
            "x1 Dm_5fr 1 F_1fr 1 Bb_6fr 1 C_8fr 1",
            "> 0"
          ]
        }
      ]
    },
    "c2": {
      "name": "chorus 2",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": [
            "x3 F_1fr 1 C_3fr 1 Dm_5fr 1 A_5fr 1 / 0 Bb_6fr 1 C_8fr 1 F_1fr 1 C_8fr 1",
            "> 0"
          ]
        }
      ]
    },
    "o1": {
      "name": "outro pt.1",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x1 F_1fr 8", "> 2"]
        }
      ]
    },
    "o2": {
      "name": "outro pt.2",
      "times": 3,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": [
            "x1 F_1fr 1 Bb_1fr 1 F_1fr 1 C_3fr 1 / 0 F_1fr 1 Bb_1fr 1",
            "> 2",
            "x1 C_3fr 1 Bb_1fr 1",
            "> 3",
            "x1 F_1fr 1",
            "> 2"
          ]
        }
      ]
    }
  },
  "order": ["i", "v", "c1", "v2", "c2", "o1", "o2"],
  "lyrics": false,
  "pdf": false,
  "res": [
    {
      "alias": "Struggling with Barre Chords? Learn “Flake” by Jack Johnson (Guitar Lesson)",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/rcpsgFHaFF8"
    }
  ]
}

=== TheAncientOwl/book-of-frets-x/songs/all-of-me/config.json
{
  "version": "2.1.0",
  "contributors": ["TheAncientOwl"],
  "title": "All Of Me",
  "artists": ["John Legend"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 1,
  "chordIDs": ["Em", "C", "G", "D", "Am"],
  "strumms": [
    ["De", "D", "D", "De", "D", "D", "De", "D"],
    ["D"],
    ["D", "-", "D", "U", "D", "-", "D", "U", "-", "U", "D", "-", "D", "U", "D", "U"]
  ],
  "sections": {
    "i": {
      "name": "intro",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x1 Em 1 C 1 G 1 D 1", "> 0"]
        }
      ]
    },
    "v": {
      "name": "verse",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x4 Em 1 C 1 G 1 D 1", "> 0"]
        }
      ]
    },
    "p": {
      "name": "prechorus",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x1 Am 1 Am 1 G 1 D 1 / 0 Am 1 Am 1 G 1", "> 0", "x1 D 1", "> 1"]
        }
      ]
    },
    "c1": {
      "name": "chorus 1",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x2 G 1 Em 1 C 1 D 1", "> 2", "x2 Em 1 C 1 G 1 D 1", "> 0"]
        }
      ]
    },
    "c2": {
      "name": "chorus 2",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": [
            "x1 G 1 Em 1 C 1 D 1",
            "> 1",
            "x1 G 1 Em 1 C 1 D 1",
            "> 2",
            "x3 Em 1 C 1 G 1 D 1",
            "> 0",
            "x1 Em 1 C 1 G 1 D 1",
            "> 1"
          ]
        }
      ]
    }
  },
  "order": ["i", "v", "p", "c1", "v", "p", "c1", "p", "c2"],
  "lyrics": false,
  "pdf": false,
  "res": [
    {
      "alias": "All Of Me Guitar Tutorial - John Legend Guitar Lesson 🎸 |Easy Chords + Guitar Cover|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/HmG_oPsUVTs"
    },
    {
      "alias": "All Of Me Guitar Cover - John Legend 🎸 |Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/nrlMBzg06Js"
    }
  ]
}

=== TheAncientOwl/book-of-frets-x/public/songs/new-heart/config.json
{
  "version": "2.1.0",
  "contributors": ["TheAncientOwl"],
  "title": "New Heart",
  "artists": ["Crash Adams"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 0,
  "chordIDs": ["Am", "Dm", "G", "C", "E"],
  "strumms": [
    ["D", "U", "Dx", "U", "-", "U", "Dx", "U", "-"],
    ["D"],
    ["D", "-", "-", "-"],
    ["D", "D", "D"]
  ],
  "sections": {
    "i": {
      "name": "intro",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x1 Am 1 Am 1 | 0 Dm 1 Dm 1 / 0 G 1 G 1 | 0 C 1 E 1", "> 0"]
        }
      ]
    },
    "v1": {
      "name": "verse 1",
      "times": 1,
      "entries": [
        { "renderer": "chords-v2", "data": ["x1 Am 1 Am 1 | 0 Dm 1 Dm 1 / 0 G 1 G 1", "> 0"] },
        { "renderer": "chords-v2", "data": ["x1 C 1 ? 0 E 1", "> 2 3"] }
      ]
    },
    "c1": {
      "name": "chorus 1",
      "times": 2,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x1 Am 1 Am 1 | 0 Dm 1 Dm 1 / 0 G 1 G 1 | 0 C 1", "> 0"]
        },
        { "renderer": "chords-v2", "data": ["x1 E 1", "> 3"] }
      ]
    },
    "v2": {
      "name": "verse 2",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": [
            "x1 Am 1 Am 1 | 0 Dm 1 Dm 1 / 0 G 1 G 1 | 0 C 1 E 1",
            "x1 Am 1 Am 1 | 0 Dm 1 Dm 1 / 0 G 1 G 1",
            "> 0"
          ]
        },
        {
          "renderer": "chords-v2",
          "data": ["x1 C 1 ? 0 E 1", "> 2 3"]
        }
      ]
    },
    "c2": {
      "name": "chorus 2",
      "times": 3,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x1 Am 1 Am 1 | 0 Dm 1 Dm 1 / 0 G 1 G 1 | 0 C 1", "> 0"]
        },
        {
          "renderer": "chords-v2",
          "data": ["x1 E 1", "> 3"]
        }
      ]
    },
    "pc": {
      "name": "post-chorus",
      "times": 1,
      "entries": [
        { "renderer": "chords-v2", "data": ["x1 Am 1 Dm 1 G 1 C 1", "> 1", "x1 E 1", "> 3"] }
      ]
    },
    "o1": {
      "name": "outro",
      "times": 2,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x1 Am 1 Am 1 | 0 Dm 1 Dm 1 / 0 G 1 G 1 | 0 C 1", "> 0", "x1 E 1", "> 3"]
        }
      ]
    },
    "o2": {
      "name": "outro",
      "times": 1,
      "entries": [{ "renderer": "chords-v2", "data": ["x1 Am 1", "> 1"] }]
    }
  },
  "order": ["i", "v1", "c1", "v2", "c2", "pc", "o1", "o2"],
  "lyrics": false,
  "pdf": false,
  "res": [
    {
      "alias": "967.Crash Adams - New Heart 기타커버【★★☆☆☆】 | Guitar tutorial 【TAB譜】",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/0G-Yxj_j9o4"
    }
  ]
}

=== TheAncientOwl/book-of-frets-x/public/songs/wake-me-up/config.json
{
  "version": "2.0.0",
  "contributors": ["TheAncientOwl"],
  "title": "Wake Me Up",
  "artists": ["Avicii"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 2,
  "chordIDs": ["Am", "Ft", "G", "C/G", "E"],
  "strumms": [
    ["D", "-", "D", "-", "-", "U", "D", "U"],
    ["D", "-", "D", "U"]
  ],
  "sections": {
    "i": {
      "name": "intro",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["0 Am 1 Ft 1 C/G 2"], ["1 G 1"]]]
            },
            {
              "times": 1,
              "items": [[["0 Am 1 Ft 1 C/G 2"], ["1 E 1"]]]
            }
          ]
        }
      ]
    },
    "c": {
      "name": "chorus",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["0 Am 1 Ft 1 C/G 2"], ["1 G 1"]]]
            },
            {
              "times": 1,
              "items": [[["0 Am 1 Ft 1 C/G 2"], ["1 E 1"]]]
            }
          ]
        }
      ]
    },
    "d": {
      "name": "dance",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["0 Am 1 Ft 1 C/G 2"], ["1 G 1"]]]
            },
            {
              "times": 1,
              "items": [[["0 Am 1 Ft 1 C/G 2"], ["1 E 1"]]]
            }
          ]
        }
      ]
    },
    "v": {
      "name": "verse",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["0 Am 1 Ft 1 C/G 2"]]]
            }
          ]
        }
      ]
    }
  },
  "order": ["i", "c", "d", "v"],
  "lyrics": false,
  "pdf": false,
  "res": [
    {
      "alias": "Wake Me Up Guitar Tutorial - Avicii Guitar Lesson 🎸|100% Accurate Chords + Lead + No Capo + Cover|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://www.youtube.com/watch?v=_u4wlBmXGmw&t=202s"
    },
    {
      "alias": "Wake Me Up Guitar Cover Acoustic - Avicii 🎸 |Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://www.youtube.com/watch?v=ttQ4zKNH3l0"
    }
  ]
}
