=== TheAncientOwl/book-of-frets-x/project/schemas/song.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Song Schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "version": {
      "type": "string",
      "pattern": "^\\d+\\.\\d+\\.\\d+$",
      "default": "2.0.0"
    },
    "contributors": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "title": {
      "type": "string"
    },
    "artists": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "type": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["acoustic", "electric"]
      }
    },
    "notes": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "capo": {
      "type": "integer",
      "minimum": 0
    },
    "chordIDs": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "strumms": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "string",
          "enum": ["D", "U", "-", "Dx", "Ux", "X", "De", "Ue", "|"]
        },
        "minItems": 1
      }
    },
    "sections": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": { "type": "string" },
          "times": { "type": "number", "default": 1, "minimum": 1 },
          "entries": {
            "type": "array",
            "items": {
              "oneOf": [
                {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "renderer": { "type": "string", "enum": ["chords-v1"] },
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "properties": {
                          "times": { "type": "number", "default": 1 },
                          "items": {
                            "type": "array",
                            "items": {
                              "type": "array",
                              "items": {
                                "type": "array",
                                "items": {
                                  "type": "string",
                                  "pattern": "^[0-9]+(?: [A-Za-z0-9#/()_+-|]+ [0-9]+)+$"
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  },
                  "required": ["renderer", "data"]
                },
                {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "renderer": { "type": "string", "enum": ["chords-v2"] },
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "string",
                        "oneOf": [
                          {
                            "pattern": "^x\\d+(?: [A-Za-z0-9#/()_+-|!]+ [0-9]+)+$"
                          },
                          {
                            "pattern": "^>\\s*(?:\\d+\\s*)+$"
                          }
                        ]
                      }
                    }
                  },
                  "required": ["renderer", "data"]
                },
                {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "renderer": { "type": "string", "enum": ["chords-v3"] },
                    "data": {
                      "type": "object",
                      "additionalProperties": false,
                      "properties": {
                        "times": {
                          "type": "number",
                          "default": 1
                        },
                        "items": {
                          "type": "array",
                          "items": {
                            "type": "array",
                            "items": {
                              "type": "string",
                              "oneOf": [
                                {
                                  "pattern": "^x\\d+(?: [A-Za-z0-9#/()_+-|!]+ [0-9]+)+$"
                                },
                                {
                                  "pattern": "^>\\s*(?:\\d+\\s*)+$"
                                }
                              ]
                            }
                          }
                        }
                      },
                      "required": ["times", "items"]
                    }
                  },
                  "required": ["renderer", "data"]
                },
                {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "renderer": { "type": "string", "enum": ["gtab-v1"] },
                    "data": { "type": "string" }
                  },
                  "required": ["renderer", "data"]
                }
              ]
            }
          }
        },
        "required": ["name", "times", "entries"]
      }
    },
    "order": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "lyrics": {
      "type": "boolean",
      "default": false
    },
    "pdf": {
      "type": "boolean",
      "default": false
    },
    "res": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "alias": {
            "type": "string",
            "pattern": ".+"
          },
          "author": {
            "type": "string",
            "pattern": ".+"
          },
          "link": {
            "type": "string",
            "anyOf": [{ "format": "uri" }, { "pattern": "^\\{book-of-frets-x\\}#/.*" }]
          }
        },
        "required": ["alias", "author", "link"]
      }
    }
  },
  "required": [
    "version",
    "contributors",
    "title",
    "artists",
    "type",
    "notes",
    "capo",
    "chordIDs",
    "strumms",
    "sections",
    "order",
    "lyrics",
    "res"
  ]
}

=== TheAncientOwl/book-of-frets-x/public/songs/someone-you-loved/config.json
{
  "version": "2.0.0",
  "contributors": ["TheAncientOwl"],
  "title": "Someone You Loved",
  "artists": ["Lewis Capaldi"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 1,
  "chordIDs": ["C", "G", "Am", "F", "Dm"],
  "strumms": [],
  "sections": {
    "mv1": {
      "name": "main riff var.",
      "times": 1,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "[C] - A3+e0 - G0 - e0 - G0 - e0 - G0 - e0 - G0 - | [G] - E3+B0 - D0 - B0 - D0 - B0 - D0 - B0 - D0 - | [Am] - A0+B1 - D2 - B1 - D2 - B1 - D2 - B1 - D2 - | [F] - E1+G2 - A3 - G2 - A3 - G2 - A3 - G0 - A3 -"
        }
      ]
    },
    "m1": {
      "name": "main riff",
      "times": 1,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "[C] - A3+e0 - G0 - e0 - G0 - e0 - G0 - e0 - G0 - | [G] - E3+B0 - D0 - B0 - D0 - B0 - D0 - B0 - D0 - | [Am] - A0+B1 - D2 - B1 - D2 - B1 - D2 - B1 - D2 - | [F] - E1+G2 - A3 - G2 - A3 - G2 - A3 - G2 - A3 -"
        }
      ]
    },
    "m2": {
      "name": "main riff",
      "times": 3,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "[C] - A3+e0 - G0 - e0 - G0 - e0 - G0 - e0 - G0 - | [G] - E3+B0 - D0 - B0 - D0 - B0 - D0 - B0 - D0 - | [Am] - A0+B1 - D2 - B1 - D2 - B1 - D2 - B1 - D2 - | [F] - E1+G2 - A3 - G2 - A3 - G2 - A3 - G2 - A3 -"
        }
      ]
    },
    "m3": {
      "name": "main riff",
      "times": 4,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "[C] - A3+e0 - G0 - e0 - G0 - e0 - G0 - e0 - G0 - | [G] - E3+B0 - D0 - B0 - D0 - B0 - D0 - B0 - D0 - | [Am] - A0+B1 - D2 - B1 - D2 - B1 - D2 - B1 - D2 - | [F] - E1+G2 - A3 - G2 - A3 - G2 - A3 - G2 - A3 -"
        }
      ]
    },
    "b": {
      "name": "bridge",
      "times": 1,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "[Dm] - D0+e1 - G2 - e1 - G2 - e1 - G2 - e1 - G2 - | [Am] - A0+B1 - D2 - B1 - D2 - B1 - D2 - B1 - D2 - | [G] - E3+B0 - D0 - B0 - D0 - B0 - D0 - B0 - D0 - | [G] - E3+B0 - D0 - B0 - D0 - [Am] - A0+B1 - D2 - B1 - D2 -"
        },
        {
          "renderer": "gtab-v1",
          "data": "[Dm] - D0+e1 - G2 - e1 - G2 - e1 - G2 - e1 - G2 - | [Am] - A0+B1 - D2 - B1 - D2 - B1 - D2 - B1 - D2 - | [G] - E3+B0 - D0 - B0 - D0 - B0 - D0 - B0 - D0 - | - - - - - - - - - - - - - - - - - -"
        }
      ]
    },
    "sc": {
      "name": "soft chorus",
      "times": 1,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "[C] - A3+B1+e0 - - - - - - - - - - - - - - - | [G] - E3+G0+B0 - - - - - - - - - - - - - - - | [Am] - A0+G2+B1 - - - - - - - - - - - - - - - | [F] - E1+D3+G2 - - - - - - - - - - - - - - -"
        },
        {
          "renderer": "gtab-v1",
          "data": "[C] - A3+B1+e0 - - - - - - - - - - - - - - - | [G] - E3+G0+B0 - - - - - - - - - - - - - - - | [Am] - A0+B1 - D2 - B1 - D2 - B1 - D2 - B1 - D2 - | [F] - E1+G2 - A3 - G2 - A3 - G2 - A3 - G0 - A3 -"
        }
      ]
    },
    "o": {
      "name": "outro",
      "times": 1,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "[C] A3+D2+G0+B1+e0 - - - - - - - - - - - - - - - | [G] - E3+A2+D0+G0+B0 - - - - - - - - - - - - - - - | [Am] - A0+D2+G2+B1+e0 - - - - - - - - - - - - - - - | [F] - E1+A3+D3+G2+B1 - - - - - - - - - - - - - - -"
        }
      ]
    }
  },
  "order": ["mv1", "m1", "mv1", "m2", "mv1", "m1", "mv1", "m3", "b", "sc", "m1", "mv1", "o"],
  "lyrics": false,
  "pdf": false,
  "res": [
    {
      "alias": "Someone You Loved Guitar Tutorial Lewis Capaldi Guitar Lesson 🎸|Fingerpicking + Easy Chords + TAB|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/Z0OcYM5tixs"
    },
    {
      "alias": "Someone You Loved Guitar Cover Lewis Capaldi 🎸 |Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/f8RdxRNM6nQ"
    }
  ]
}

=== TheAncientOwl/book-of-frets-x/songs/the-times-they-are-a-changin/config.json
{
  "version": "2.0.0",
  "contributors": ["TheAncientOwl"],
  "title": "The Times They Are A Changin'",
  "artists": ["Bob Dylan"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 3,
  "chordIDs": ["G", "Em", "C", "Csus2", "G/B"],
  "strumms": [["D", "-", "D", "U", "D", "U"]],
  "sections": {
    "i": {
      "name": "intro",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["0 G 1 G 1 G 1"]]]
            }
          ]
        }
      ]
    },
    "v1": {
      "name": "verse 1",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [
                [
                  [
                    "0 G 1 Em 1 C 1 G 1 G 1",
                    "00 G 1 Em 1 C 1 D 1",
                    "0 G 1 Em 1 C 1 G 1 G 1 G 1",
                    "0 G 1 Am 1 D 1 D 1",
                    "0 D 1 Csus2 1 G/B 1 D 1",
                    "0 G 1 G 1 D 1 G 1"
                  ]
                ]
              ]
            }
          ]
        }
      ]
    },
    "b1": {
      "name": "break 1",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["0 G 1 Em 1 C 1 G 1 G 1 G 1 G 1"]]]
            }
          ]
        }
      ]
    },
    "v2": {
      "name": "verse 2",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [
                [
                  [
                    "0 G 1 Em 1 C 1 G 1 G 1",
                    "0 G 1 Em 1 C 1 D 1",
                    "0 G 1 Em 1 C 1 G 1 G 1",
                    "0 G 1 Am 1 D 1 D 1",
                    "0 D 1 Csus2 1 G/B 1 D 1",
                    "0 G 1 G 1 D 1"
                  ]
                ]
              ]
            }
          ]
        }
      ]
    },
    "b2": {
      "name": "break 2",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["0 G 1 Em 1 C 1 G 1 G 1", "0 D 1 Csus2 1 G/B 1 D 1", "0 D 1 D 1 D 1"]]]
            }
          ]
        }
      ]
    },
    "v3": {
      "name": "verse 3",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [
                [
                  [
                    "0 G 1 Em 1 C 1 G 1 G 1",
                    "0 G 1 Em 1 C 1 D 1",
                    "0 G 1 Em 1 C 1 G 1 G 1",
                    "0 G 1 Am 1 D 1 D 1",
                    "0 D 1 Csus2 1 G/B 1 D 1",
                    "0 G 1 C 1 D 1 G 1"
                  ]
                ]
              ]
            }
          ]
        }
      ]
    },
    "b3": {
      "name": "break 3",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["0 G 1 D 1 Csus2 1 D 1 G 1 G 1"]]]
            }
          ]
        }
      ]
    },
    "v4": {
      "name": "verse 4",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [
                [
                  [
                    "0 G 1 Em 1 C 1 G 1 G 1",
                    "0 G 1 Em 1 C 1 D 1",
                    "0 G 1 Em 1 C 1 G 1 G 1",
                    "0 G 1 Am 1 D 1 D 1",
                    "0 G 1 Csus2 1 G/B 1 D 1",
                    "0 G 1 C 1 D 1 G 1"
                  ]
                ]
              ]
            }
          ]
        }
      ]
    },
    "b4": {
      "name": "break 4",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [
                [
                  [
                    "0 G 1 Em 1 C 1 G 1 G 1",
                    "0 D 1 Csus2 1 G/B 1 D 1 D 1",
                    "0 G 1 C 1 D 1 G 1",
                    "0 G 1 G 1 G 1"
                  ]
                ]
              ]
            }
          ]
        }
      ]
    },
    "v5": {
      "name": "verse 5",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [
                [
                  [
                    "0 G 1 Em 1 C 1 G 1 G 1",
                    "0 G 1 Em 1 C 1 D 1",
                    "0 G 1 Em 1 C 1 G 1 G 1",
                    "0 G 1 Em 1 C 1 G 1 G 1",
                    "0 D 1 Csus2 1 G/B 1 D 1",
                    "0 G 1 C 1 D 1 G 1"
                  ]
                ]
              ]
            }
          ]
        }
      ]
    },
    "o": {
      "name": "outro",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["0 G 1 Em 1 C 1 G 1"]]]
            }
          ]
        }
      ]
    }
  },
  "order": ["i", "v1", "b1", "v2", "b2", "v3", "b3", "v4", "b4", "v5", "o"],
  "lyrics": false,
  "pdf": false,
  "res": [
    {
      "alias": "The Times They Are A Changin' Guitar Tutorial Bob Dylan Guitar Lesson |Easy Chords + Strumming|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/oX8_Oshrggc"
    },
    {
      "alias": "The Times They Are A Changin' Guitar Cover Bob Dylan 🎸|Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/Qw2mDG9TTQo"
    }
  ]
}

=== TheAncientOwl/book-of-frets-x/songs/someone-you-loved-easy/config.json
{
  "version": "2.0.0",
  "contributors": ["TheAncientOwl"],
  "title": "Someone You Loved | Easy",
  "artists": ["Lewis Capaldi"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 1,
  "chordIDs": ["C", "G", "Am", "F", "Dm"],
  "strumms": [["D", "-", "D", "U", "-", "U", "D", "U"], ["D", "-", "D", "U"], ["D"]],
  "sections": {
    "m1": {
      "name": "main progression",
      "times": 13,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["0 C 1 G 1 Am 1 F 1"]]]
            }
          ]
        }
      ]
    },
    "b": {
      "name": "bridge",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["0 Dm 1 Am 1 G 1"], ["1 G 1 Am 1"], ["0 Dm 1 Am 1 G 1"]]]
            }
          ]
        }
      ]
    },
    "m2": {
      "name": "main progression",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v1",
          "data": [
            {
              "times": 1,
              "items": [[["2 C 1 G 1 Am 1 F 1"]]]
            },
            {
              "times": 1,
              "items": [[["2 C 1 G 1"], ["0 Am 1 F 1"]]]
            },
            {
              "times": 2,
              "items": [[["0 C 1 G 1 Am 1 F 1"]]]
            },
            {
              "times": 1,
              "items": [[["2 C 1 G 1 Am 1 F 1"], ["2 C 1"]]]
            }
          ]
        }
      ]
    }
  },
  "order": ["m1", "b", "m2"],
  "lyrics": false,
  "pdf": false,
  "res": [
    {
      "alias": "Someone You Loved Guitar Tutorial Lewis Capaldi Guitar Lesson 🎸|Fingerpicking + Easy Chords + TAB|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/Z0OcYM5tixs"
    },
    {
      "alias": "Someone You Loved Guitar Cover Lewis Capaldi 🎸 |Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/f8RdxRNM6nQ"
    }
  ]
}

=== TheAncientOwl/book-of-frets-x/songs/no-surprises/config.json
{
  "version": "2.1.0",
  "contributors": ["TheAncientOwl"],
  "title": "No Surprises",
  "artists": ["Radiohead"],
  "type": ["acoustic", "electric"],
  "notes": ["Lift middle finger after highlighted strum (optional)"],
  "capo": 3,
  "chordIDs": ["D", "Gm6", "G6/B", "A", "Asus4"],
  "strumms": [
    ["De", "U", "D", "-", "D", "-", "D", "U"],
    ["D", "U", "D", "U", "D", "U", "D", "U"],
    ["D", "-", "D", "-", "D", "-", "D", "U"],
    ["D", "-", "D", "-", "D", "-", "-", "-"]
  ],
  "sections": {
    "r": {
      "name": "riff",
      "times": 2,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "- [D] e2 - G2 - B3 - G2 - e2 - G2 - B3 - G2 - | - e2 - G2 - B3 - G2 - [Gm6] E3 - G3 - B3 - e0 -"
        }
      ]
    },
    "br": {
      "name": "break",
      "times": 1,
      "entries": [{ "renderer": "chords-v2", "data": ["x2 D 1 D 1 | 0 D 1 ! 0 Gm6 1", "> 0 1"] }]
    },
    "v1": {
      "name": "verse 1",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": [
            "x1 D 1 D 1 | 0 D 1 D 1 / 0 G6/B 1 G6/B 1 | 0 G6/B 1 G6/B 1",
            "> 0",
            "x1 Em 1 Em 1 | 0 A 1 A 1",
            "> 2"
          ]
        }
      ]
    },
    "br_x1": {
      "name": "break",
      "times": 1,
      "entries": [{ "renderer": "chords-v2", "data": ["x1 D 1 D 1 | 0 D 1 ! 0 Gm6 1", "> 0 1"] }]
    },
    "v2": {
      "name": "verse 2",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x1 D 1 D 1 | 0 D 1 D 1 / 0 G6/B 1 G6/B 1 | 0 G6/B 1 G6/B 1", "> 0"]
        }
      ]
    },
    "c": {
      "name": "chorus",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x2 Em 1 Em 1 | 0 A 1 A 1", "x1 Em 1 Em 1 | 0 A 1", "> 2", "x1 A 1", "> 3"]
        }
      ]
    },
    "bdg": {
      "name": "bridge",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x2 A 1 Asus4 1 Gm6 1 ! 0 Gm6 1", "> 2 1"]
        },
        {
          "renderer": "chords-v2",
          "data": ["x1 Em 1 Em 1 | 0 Gm6 1 Gm6 1", "> 2"]
        }
      ]
    }
  },
  "order": [
    "r",
    "br",
    "v1",
    "br_x1",
    "v1",
    "br_x1",
    "v2",
    "c",
    "r",
    "v2",
    "c",
    "br_x1",
    "bdg",
    "v2",
    "c",
    "r"
  ],
  "lyrics": false,
  "pdf": false,
  "res": [
    {
      "alias": "No Surprises Guitar Tutorial Radiohead Guitar Lesson |Riff + Chords + TAB|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/pjzDr2cyeJs"
    },
    {
      "alias": "No Surprises Guitar Cover Radiohead 🎸|Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/FJq0qfTcGok"
    }
  ]
}

=== TheAncientOwl/book-of-frets-x/public/songs/birds-of-a-feather-easy/config.json
{
  "version": "2.0.0",
  "contributors": ["TheAncientOwl"],
  "title": "Birds Of A Feather (Easy)",
  "artists": ["Billie Eilish"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 0,
  "chordIDs": ["D", "Em7_v2", "Bm7", "A"],
  "strumms": [["D", "-", "-", "U", "D", "U", "D", "-", "-", "U", "D", "U", "D", "-", "D", "U"]],
  "sections": {
    "i": {
      "name": "intro",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x1 D 1 D 1", "> 0"]
        }
      ]
    },
    "mp": {
      "name": "main progression",
      "times": 11,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x1 D 1 D 1 Bm7 1 Bm7 1", "x1 Em7_v2 1 Em7_v2 1 A 1 A 1", "> 0"]
        }
      ]
    }
  },
  "order": ["i", "mp"],
  "lyrics": false,
  "pdf": false,
  "res": [
    {
      "alias": "Birds Of A Feather Guitar Tutorial Billie Eilish Guitar Chords + Fingerpicking",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/mkx4ZNN4hoQ"
    },
    {
      "alias": "Birds Of A Feather Guitar Cover Billie Eilish 🎸|Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/aPCfY2fHA08"
    }
  ]
}

=== TheAncientOwl/book-of-frets-x/public/songs/crazy-little-thing-called-love/config.json
{
  "version": "2.1.0",
  "contributors": ["TheAncientOwl"],
  "title": "Little Thing Called Love",
  "artists": ["Queen"],
  "type": ["acoustic"],
  "notes": ["On D chord, 2nd down strum, pinky finger down => Dsus4"],
  "capo": 0,
  "chordIDs": ["D", "Dsus4", "G", "C", "Bb", "E", "A"],
  "strumms": [
    ["D", "U", "D", "U", "-", "U", "D", "U"],
    ["D", "U", "D", "U"],
    ["D", "-", "D", "-", "D", "U", "D", "-"],
    ["D", "U", "D", "U", "D", "U", "D", "U"],
    ["D", "-", "D", "U", "D", "U", "D", "U"],
    ["D", "-", "D"],
    ["D"]
  ],
  "sections": {
    "i": {
      "name": "intro",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x1 D 4", "> 0"]
        }
      ]
    },
    "v": {
      "name": "verse",
      "times": 2,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x2 D 2 G 2 ? 0 C 1 G 1", "> 0 1"]
        },
        {
          "renderer": "chords-v2",
          "data": ["x1 D 1 ? 0 Bb 1 C 1 ? 0 D 2", "> 0 1 0"]
        }
      ]
    },
    "c1": {
      "name": "chorus 1",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x1 G 2 ? 0 C 1 ? 0 G 1", "> 0 2 0"]
        },
        {
          "renderer": "chords-v2",
          "data": ["x1 Bb 2 ? 0 E 1 A 1 ? 0 F 1", "> 3 1 6"]
        }
      ]
    },
    "c2": {
      "name": "chorus 2",
      "times": 1,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "- - - - A5 - A4 - A3 - - | - - - - E5 - E4 - E3 - - | - E0+A2+D2+G1+B0 - E0+A2+D2+G1+B0 - E0+A2+D2+G1+B0 - E0+A2+D2+G1+B0 - E0+A2+D2+G1+B0 - E0+A2+D2+G1+B0 - | - G2 - G2 - G0 - G0 - D4 - D4 - D2 - D2 -"
        }
      ]
    },
    "s1": {
      "name": "solo 1",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x1 Bb 2 ? 0 D 1 ? 0 G 1 ? 0 D 1", "> 4 5 1 4"]
        },
        {
          "renderer": "chords-v2",
          "data": ["x1 Bb 2 ? 0 D 1 ? 0 E 1 A 1 ? 0 F 1", "> 4 5 1 6"]
        }
      ]
    },
    "s2": {
      "name": "solo 2",
      "times": 1,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "- - - - A5 - A4 - A3 - - | - - - - E5 - E4 - E3 - - | - E0+A2+D2+G1+B0 - E0+A2+D2+G1+B0 - E0+A2+D2+G1+B0 - E0+A2+D2+G1+B0 - E0+A2+D2+G1+B0 - E0+A2+D2+G1+B0 - | - A0+D2+G2+B2 - - - - - - - - - - - - - - -"
        }
      ]
    },
    "o": {
      "name": "outro",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x2 D 2 G 1 ? 0 C 1 G 1", "> 0 1"]
        },
        {
          "renderer": "chords-v2",
          "data": ["x1 D 1", "> 0"]
        },
        {
          "renderer": "chords-v2",
          "data": ["x6 Bb 1 C 1 ? 0 D 1", "> 1 0"]
        }
      ]
    }
  },
  "order": ["i", "v", "v", "c1", "c2", "v", "s1", "s2", "o"],
  "lyrics": false,
  "pdf": false,
  "res": [
    {
      "alias": "Crazy Little Thing Called Love Guitar Tutorial - Queen Guitar Lesson 🎸 |TABS + Easy Chords + Solo|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/d5BMMbEfg-o"
    },
    {
      "alias": "Crazy Little Thing Called Love Guitar Cover Acoustic - Queen 🎸 |Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/9gGc45WjnpY"
    }
  ]
}

=== TheAncientOwl/book-of-frets-x/public/songs/lovely/config.json
{
  "version": "2.0.0",
  "contributors": ["TheAncientOwl"],
  "title": "Lovely",
  "artists": ["Billie Eilish", "Khalid"],
  "type": ["acoustic"],
  "notes": [],
  "capo": 0,
  "chordIDs": ["C", "Em", "Bm"],
  "strumms": [["D", "-", "D", "U", "D", "U", "D", "U"], ["D"]],
  "sections": {
    "i1": {
      "name": "intro",
      "times": 1,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "[C] - G9 - B8 - G9 - B8 - G9 - B8 - G9 - B8 - | - G9 - B8 - G9 - B8 - G9 - B8 - G9 - B8 -"
        }
      ]
    },
    "i2": {
      "name": "intro",
      "times": 4,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "[C] - E9+G9 - B8 - G9 - B8 - G9 - B8 - G9 - B8 - | - G9 - B8 - G9 - B8 - G9 - B8 - G9 - B8 - | [Em] - E0+G9 - B8 - G9 - B8 - G9 - B8 - G9 - B8 - | [Bm] - E7+G7 - B7 - G7 - B7 - G7 - B7 - G7 - B7 -"
        }
      ]
    },
    "pc": {
      "name": "prechorus",
      "times": 4,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x1 C 1 C 1 Em 1 Bm 1", "> 0"]
        }
      ]
    },
    "c": {
      "name": "chorus",
      "times": 2,
      "entries": [
        {
          "renderer": "chords-v2",
          "data": ["x1 C 1 - 1 Em 1 Bm 1", "> 1"]
        }
      ]
    },
    "b": {
      "name": "break",
      "times": 1,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "[C] - E8+G9 - B8 - G9 - B8 - G9 - B8 - G9 - B8 - | - G9 - B8 - G9 - B8 - G9 - B8 - G9 - B8 -"
        }
      ]
    },
    "v": {
      "name": "verse",
      "times": 2,
      "entries": [
        {
          "renderer": "gtab-v1",
          "data": "[C] - E9+G9 - B8 - G9 - B8 - G9 - B8 - G9 - B8 - | - G9 - B8 - G9 - B8 - G9 - B8 - G9 - B8 - | [Em] - E0+G9 - B8 - G9 - B8 - G9 - B8 - G9 - B8 - | [Bm] - E7+G7 - B7 - G7 - B7 - G7 - B7 - G7 - B7 -"
        }
      ]
    },
    "o": {
      "name": "outro",
      "times": 1,
      "entries": [
        {
          "renderer": "chords-v3",
          "data": {
            "times": 2,
            "items": [["x1 C 1 C 1 Em 1 Bm 1", "> 0"]]
          }
        },
        {
          "renderer": "chords-v3",
          "data": {
            "times": 2,
            "items": [["x1 C 1 - 1 Em 1 Bm 1", "> 1"]]
          }
        }
      ]
    }
  },
  "order": ["i1", "i2", "pc", "c", "b", "v", "pc", "c", "o"],
  "lyrics": false,
  "res": [
    {
      "alias": "Lovely Guitar Tutorial Billie Eilish Guitar |Chords + Fingerpicking|",
      "author": "GuitarZero2Hero ~ YouTube",
      "link": "https://youtu.be/QKQr9HgkuFk"
    },
    {
      "alias": "Lovely Guitar Cover Billie Eilish 🎸|Tabs + Chords|",
      "author": "GuitarZero2Hero Express ~ YouTube",
      "link": "https://youtu.be/1MRVR_c7qQw"
    }
  ]
}
